export { Footer } from './Footer/Footer'
export { Header } from './Header/Header'
export { Search, type FilterParams } from './Search/Search'
export { MoviesList } from './MoviesList/MoviesList'
export { MovieCard } from './MovieCard/MovieCard'
export { AuthForm } from './AuthForm/AuthForm'
export { Profile } from './Profile/Profile'
